---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ray-worker
  labels:
    app: ray-worker
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ray-worker
    spec:
      containers:
      - name: ray-worker
        image: us.gcr.io/prophet-158422/ray
        ports:
        - containerPort: 12345
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP 
        command: [ "/bin/bash", "-c", "--" ]
        args: ["/ray/scripts/start_ray.sh --node-ip-address $MY_POD_IP --redis-address $(python -c 'import socket;import sys; sys.stdout.write(socket.gethostbyname(\"ray-head.default.svc.cluster.local\"));sys.stdout.flush()'):6379 --object-manager-port 12345 && while true; do sleep 30; done;"]
